name: engage
description: Engage flutter SDK.
version: 0.1.0
homepage: https://engage.so/

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  http: ^0.13.4
  package_info_plus: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: